# -*- coding: utf-8 -*-
"""Angulo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10rvfc-MNWMQE8d0JhnXysll1jTl7-Zyt
"""

#Se importa el archivo, y asi poder hacer uso de la clase  
from Taylor import Calculo

if __name__ == "__main__":
# Se solicita un angulo al usuario
    angulo = int(input("Escribe un angulo:"))
    def SenoTaylor(grados,error=0.000001):
        senotaylor = SenoTaylor(angulo)
    #Se imprime el seno del angulo proporcionado    
    print("El sin de", str(angulo),"° es:",SenoTaylor)